title: Inteligencia Artificial — Ingeniería
description: Curso interactivo de Introducción a la Inteligencia Artificial aplicada a problemas reales de Ciencia e Ingeniería
baseurl: "/Inteligencia-Artificial"
url: "https://ecuadros.github.io"
theme: null
markdown: kramdown
